[package]
name = "kittysay"
version = "0.4.0"
authors = ["uncenter <uncenter@uncenter.dev>"]
license = "MIT"
description = "The cutest successor of cowsay."
readme = "README.md"
homepage = "https://github.com/uncenter/kittysay"
repository = "https://github.com/uncenter/kittysay"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
clap-stdin = "0.4.0"
color-eyre = "0.6.2"
crossterm = "0.27.0"

[lints.clippy]
all = "warn"
pedantic = "warn"
